export const colors = {
  page: '#f7f9f6',
  pageAlt: '#f8faf8',
  surface: '#ffffff',
  surfaceElevated: '#ffffff',
  surfaceMuted: '#f4f7f4',
  surfaceSoft: '#e8f4f1',
  stroke: '#e0e8e1',
  strokeStrong: '#d3ded5',
  text: '#2d3a30',
  textMuted: '#6b7b6e',
  textSoft: '#8a9c8e',
  primary: '#4a7c59',
  primaryStrong: '#2a7a6b',
  primarySoft: '#e8f4f1',
  secondary: '#e9f0ea',
  accent: '#b26b00',
  accentSoft: '#fff4e5',
  info: '#2a7a6b',
  infoSoft: '#e8f4f1',
  success: '#4a7c59',
  successSoft: '#eaf4ed',
  warning: '#b26b00',
  warningSoft: '#fff4e5',
  danger: '#c94a4a',
  dangerSoft: '#fdecec',
  white: '#ffffff',
  shadow: 'rgba(0, 0, 0, 0.06)',
  overlay: 'rgba(45, 58, 48, 0.08)',
} as const;

export const navigationColors = {
  light: {
    text: colors.text,
    background: colors.page,
    tint: colors.primary,
    icon: colors.textSoft,
    tabIconDefault: colors.textSoft,
    tabIconSelected: colors.primaryStrong,
  },
  dark: {
    text: '#edf2ef',
    background: '#101713',
    tint: '#cfe1d5',
    icon: '#b8c5bc',
    tabIconDefault: '#9dad9f',
    tabIconSelected: '#edf2ef',
  },
} as const;
